### ISSUE TITLE
大佬您好，论文中Fig.11 的分解的曲线对应哪部分代码呀？

### ISSUE THREAD

**Issue by 943fansi** [navfour/ecoforecast#1]

**Comment by navfour** [comment]
这是可解释性的部分，需要对实验结果的输出做分析。在代码中会将不同block的结果打在result文件夹里，对block的结果做累加即可得到不同block的学习内容

**Comment by navfour** [comment]
图本身是用matlab单独画的

**Comment by lanhaoli** [comment]
我看实验结果都是分成了6块列，但是相加不等于predict的值。而且我没找到季节项和趋势项的result。大佬可以告诉一下该如何获取吗？

**Comment by lanhaoli** [comment]
> 在代码中结果部分的不同结果块中，不同的块的拼块里的拼写加了学习，对实验的结果进行了不同的输出分析。

你好大佬！我在results文件夹中只看到总预测值，和不同组合的总结果。请问季节项和趋势项的数据具体应该是在哪儿啊？

**Comment by lanhaoli** [comment]
另外，请问为什么论文中Fig.11的季节项不明显？或者说没有季节性啊?

**Comment by lanhaoli** [comment]
![image](https://user-images.githubusercontent.com/95955682/188876070-ccf1efce-5caf-4b5d-a5d3-7f57f31b9387.png)

**Comment by lanhaoli** [comment]
大佬，上面这个图是我在windows_sizes = [12]的时候，将在您给的GDP.csv数据上跑出的结果中，result-block_STG_12里的标号为0到5的列加起来的值，绘出的图。

**Comment by lanhaoli** [comment]
> _No description provided._

你好！请问你知道是怎么搞的了吗？

**Comment by navfour** [comment]
> 大佬，这个图是我在windows_sizes = [12]的时候，将在你给的GDP.csv数据上跑出的结果中，result-block_STG_12里的标号为0到5的列加起来的值，出绘的图。

不是把不同的列加起来，二是对单独的列做累加。

**Comment by navfour** [comment]
> > 在代码中结果部分的不同结果块中，不同的块的拼块里的拼写加了学习，对实验的结果进行了不同的输出分析。
> 
> 你的好大佬我在结果中只看到了多个中的总预测，和不同组合的总结果值。 问季项目和趋势项目的数据具体应该是在哪里啊？

列的顺序和block的结构式对应的，例如你用了STG，那么第0列就是S结构
